### ISSUE TITLE
Species on site but not available in drop-down

### ISSUE THREAD

**Issue by sacrevert** [BiologicalRecordsCentre/OnlinePlantAtlas#1]
From Biren:

>Oli and David…
I found one small problem which is, the search on the front page doesn’t display all species name for some reason. For example if you search ‘Sedum confusum‘ , you don’t get any result and that is the same for this http://www.brc.ac.uk/plantatlas/list_plants page. But if you type species name in the address bar or use this URL http://www.brc.ac.uk/plantatlas/plant/Sedum-confusum instead, you could see the species details. The reason, I mentioned this is because you could avoid creating a duplicate species/records. This is not for those species which have got no details stored at all in the database (included list species in the CSV files).

**Comment by BirenRathod** [comment]
The problem is that 'Sedum confusum' page is not published, so search don't get the results. There may be some more species like that so, I implemented the search so it should bring all species regardless of their publish status.

**Comment by sacrevert** [comment]
OK, that sounds good for Mark. In terms of this issue, can you create a list of those that are unpublished, and publish them?

**Comment by sacrevert** [comment]
Done offline, and also superceded by Atlas 2020 website project
