### ISSUE TITLE
Left & right arrows keys not working in taxon picker

### ISSUE THREAD

**Issue by japonicus** [BiologicalRecordsCentre/OnlinePlantAtlas#10]
There's an odd bug on the species pages. The left and right arrow keys don't move the cursor in the taxon picker field. The field works correctly on the non-species pages and on my [demo page](https://database.bsbi.org/dev/Taxonpicker/public/sppage.html). There are no errors logged in the console.

**Comment by japonicus** [comment]
The image gallery adds a keyDown event handler on the window, that interferes with arrow key presses even when the gallery tab isn't open.

I've tweaked the taxon picker code to hopefully prevent arrow key presses propagating as far as the top level image gallery handler (which attaches to window), so that arrow presses should move the caret when the input box is focused. The revised taxonpicker code is on GitHub.

**Comment by burkmarr** [comment]
I've implemented the new code.
