### ISSUE TITLE
A couple of metadata issues

### ISSUE THREAD

**Issue by japonicus** [BiologicalRecordsCentre/OnlinePlantAtlas#11]
I noticed a couple of minor issues with the species page metadata.

The author and citation_authors strings have an empty pair commas. I think [citation_authors is meant to be semi-colon delimited](https://www.monperrus.net/martin/accurate+bibliographic+metadata+and+google+scholar), but this tag is possibly deprecated anyway as the preferred approach is to list multiple citation_author tags separately (as you have done also).

Please could you add the middle initial for T.A.Humphrey

For https://plantatlas2020.org/atlas/2cd4p9h.91t ( _Ornithopus perpusillus_ )

the current url meta tags are
```
<meta name="citation_public_url" content="https://plantatlas2020.org/atlas">
<meta name="prism.url" content="https://plantatlas2020.org/atlas">
<meta name="eprints.official_url" content="https://plantatlas2020.org/atlas">
<meta name="bepress_citation_pdf_url" content="https://plantatlas2020.org/atlas">
```
Because the citation title implies that the individual species is being cited, the urls should point to https://plantatlas2020.org/atlas/2cd4p9h.91t rather than to the generic https://plantatlas2020.org/atlas

The bepress_citation_pdf_url tag is currently misplaced outside the HTML head, but I think that this tag should be omitted altogether as we don't have a pdf version of the species pages.

Sorry not to have picked these up earlier.

**Comment by burkmarr** [comment]
@japonicus - these should all be fixed. Only puzzle is the bepress_citation_pdf_url being outside the head tag. I was unable to reproduce it. But I've deleted it anyway as you suggested.
