### ISSUE TITLE
Add sitemap.xml

### ISSUE THREAD

**Issue by burkmarr** [BiologicalRecordsCentre/OnlinePlantAtlas#3]
From Tom Humphrey:

Because not all the taxon pages will be widely linked, they could be difficult for search engines to index. To promote indexing I've put together a static xml sitemap. Would it be possible for you to upload the attached file to the atlas website and to reference it from robots.txt, e.g.

Sitemap: https://plantatlas2020.org/sitemap.xml

**Comment by burkmarr** [comment]
@BirenRathod  - looks like I don't have permission to assign you.

**Comment by burkmarr** [comment]
@japonicus

**Comment by BirenRathod** [comment]
@burkmarr I can't assigned you as well. @DavidRoy can you able allow us to do that? Many thanks.

**Comment by DavidRoy** [comment]
have added @burkmarr @BirenRathod @japonicus to this repo

**Comment by japonicus** [comment]
To keep things together, have attached the xml site map that needs to be uploaded.
[sitemap.zip](https://github.com/BiologicalRecordsCentre/OnlinePlantAtlas/files/10933944/sitemap.zip)

**Comment by BirenRathod** [comment]
@burkmarr you can generate sitemap from sitemap.zip in below link. I have done couple of them for you using "BSBI Map" sitemaps in here -> https://plantatlas2020.org/admin/config/search/simplesitemap/custom

**Comment by burkmarr** [comment]
Hi @BirenRathod. I don't understand how that module works or what it is showing me. I can see three sitemaps already listed there, but I can't see their contents and I don't know what each of them is accomplishing.

Not sure if this is relevant but Tom's sitemap cannot be generated automatically by Drupal because 99% of the URLs in it are generated by our Javascript code (not nodes in the Drupal database), so we need to be able to include it 'as is'. 

Have you already added Tom's sitemap?

**Comment by BirenRathod** [comment]
@burkmarr it is easy to do. The link which mentioned above where I added three of them. you just have to follow them add more in it from sitemap.xml provided by @japonicus

**Comment by burkmarr** [comment]
Okay I will have a go. But what are the three you've already added?

**Comment by BirenRathod** [comment]
@burkmarr Those are top first three from sitemap.xml file which @japonicus uploaded up here.

**Comment by sacrevert** [comment]
@BirenRathod hi Biren, as far as I'm aware we don't need a Drupal module for this. We have an existing site map file (the one in the zipfile in Tom's comment above, not the existing one implied in the first comment in this thread). All we need is for the existing sitemap.xml file on the server to be replaced with the one in Tom's zipfile -- can you liaise with Rich directly about this please, Rich apparently does not have the required Pantheon permission to update the existing sitemap.xml file

**Comment by BirenRathod** [comment]
@japonicus can you provide him?

**Comment by japonicus** [comment]
It may be worth noting that a sitemap file doesn't itself need to be in the site's root directory, provided that it is referenced from robots.txt it can be anywhere on the server.

@BirenRathod the sitemap file is attached to my first post on this thread.

**Comment by burkmarr** [comment]
@japonicus site map is attached to this comment Biren - https://github.com/BiologicalRecordsCentre/OnlinePlantAtlas/issues/3#issuecomment-1462392373. The problem is that I don't understand how to use the module you've installed to deploy this.

**Comment by burkmarr** [comment]
@BirenRathod - are you saying that I have to add each of the entries in Tom's XML sitemap as `custom links` to the `relative drupal paths` edit box?

For example:
```
/atlas/2cd4p9h.5tb 0.8 yearly
/atlas/2cd4p9h.hbe 0.8 yearly
/atlas/2cd4p9h.w8c 0.8 yearly
```
If so, then either @japonicus or I can generate these entries in a text file instead of an XML sitemap and cut and paste the whole lot in.

**Comment by BirenRathod** [comment]
Yes, that's right @burkmarr.

**Comment by japonicus** [comment]
The list, as text file, is attached. I don't have permission to add it myself.

[taxon_list_text_version.txt](https://github.com/BiologicalRecordsCentre/OnlinePlantAtlas/files/10981212/taxon_list_text_version.txt)

**Comment by BirenRathod** [comment]
That is fantastic. @japonicus. @burkmarr just to copy and paste now.

**Comment by burkmarr** [comment]
@BirenRathod - I paste the entries (around 3,500 of them) into the custom links and save the configuration. The save times out. Usually around 1,900 of the end up being parsed and retained in the custom links. I've tried it several times. (I've also increased the setting for maximum number of entries from 2000 to 4000).

Pantheon reports the PHP timeout error. It looks like the timeout is set to 120 seconds. Are you able to increase this to 300 seconds? Let me know when you've done it and I'll retry.

**Comment by burkmarr** [comment]
@Biren - I already tried that and that doesn't work either. The sitemap.xml gets rebuilt from scratch from whatever is currently in the custom links box. And if you just append them in batches in the custom links box, you get the same problem and that list is truncated after you've saved.

**Comment by burkmarr** [comment]
@biren - I'm wondering if I should split them into different sitemaps, and use the sitemap index feature? I'm not sure how that works, but I can investigate.

**Comment by BirenRathod** [comment]
@burkmarr yes, you can.

**Comment by japonicus** [comment]
Thank for the effort you're putting into this, but it seems crazy that it's so awkward to do.

If you are able to hand-edit robots.txt then the sitemap xml file could be placed anywhere on the server (just like other static content). The structure of the site is pretty much fixed now, so there's no great utility in generating a dynamic sitemap (and there are hardly any drupal pages anyway), so a plugin seems unnecessary.

**Comment by BirenRathod** [comment]
@japonicus I understand your frustration but we don't have access to the robots.txt file. It is managed by Pantheon cloud service. If it is on our BRC server then it could possibly be exactly what you mentioned above.

**Comment by japonicus** [comment]
@BirenRathod thanks, it appears to be possible to make additions to robots.txt on Pantheon Drupal sites using composer:

https://docs.pantheon.io/bots-and-indexing#robotstxt-with-composer-and-drupal

**Comment by BirenRathod** [comment]
@burkmarr I have added and increased the PHP timeout to 300. see if that helps.

**Comment by BirenRathod** [comment]
> @BirenRathod thanks, it appears to be possible to make additions to robots.txt on Pantheon Drupal sites using composer:
> 
> https://docs.pantheon.io/bots-and-indexing#robotstxt-with-composer-and-drupal

Thanks, @japonicus . This is possible for individual sites not using custom upstream. I will look into that and find a solution if the increased PHP timeout doesn't work.

**Comment by BirenRathod** [comment]
@burkmarr I increased the timeout limit to 600 now.

**Comment by burkmarr** [comment]
@BirenRathod @japonicus - okay it's done. I guess that the timeout can be reduced again now.

**Comment by BirenRathod** [comment]
That is fantastic @burkmarr. I will reset it back to the original.

**Comment by japonicus** [comment]
That's great, thanks very much for this.
