### ISSUE TITLE
Reinstate a 404 error page, rather than a 404 homepage redirect

### ISSUE THREAD

**Issue by japonicus** [BiologicalRecordsCentre/OnlinePlantAtlas#5]
I think that as part of the discussion about redirection from the old Atlas site, there may have been misunderstanding about how 'Not Found' errors should be treated on the new site. Originally they were displaying a 'Not Found' page (with a 404 response code) - that is the correct behaviour.

Error pages are now returning the homepage content under a 404 code. That's probably slightly bad for SEO, because it lets through some URL typos. It's also problematic for the Atlas site in particular, as species pages that lack some components (e.g. trend data - see https://plantatlas2020.org/atlas/2cd4p9h.cbg ) by design attempt and fail to retrieve files. In that case they are being sent a large HTML homepage file, rather than a small error page.

Please could you restore simple 404 error pages for the Atlas site.

(this doesn't affect redirects from the old site - which go via a proxy site that filters out requests that don't match the new site and matches the old species pages with the new ones)

https://plantatlas2020.org/page-that-does-not-exist should return an error page, not a view of the homepage.

**Comment by BirenRathod** [comment]
@japonicus I have re-instated this. I think @burkmarr can do this easily.

**Comment by burkmarr** [comment]
@japonicus - this looks okay to me now. If you are happy with it, can you close the issue?
