### ISSUE TITLE
Add modal pop-up to hectad data download button

### ISSUE THREAD

**Issue by sacrevert** [BiologicalRecordsCentre/OnlinePlantAtlas#6]
It's been decided that we need a specific licence agreement for the hectad data downloads. Can we add a modal pop-up with the following message and options "ok" and "cancel", where ok proceeds with download, and cancel cancels request and returns user to the page being viewed. Pop-up message is as follows:

“By downloading these data, you agree to adhere to the terms of the [CC-BY 4.0 licence](https://creativecommons.org/licenses/by/4.0/). Please familiarise yourself with its requirements.

The recommended citation for these data is given on the right-hand side of this page under the taxon caption."

**Comment by burkmarr** [comment]
Modal box added as suggested.
