### ISSUE TITLE
Information page on the website that says what platforms we support

### ISSUE THREAD

**Issue by burkmarr** [BiologicalRecordsCentre/OnlinePlantAtlas#9]
We've had another query from someone to say that the atlas doesn't function on their 'elderly iPad' running iOS 12.5.

We could perhaps do with an information page on the atlas that indicates what platforms/browsers the software is known to run on.

**Comment by japonicus** [comment]
It might be possible to do this discreetly using https://browser-update.org/ - a script that displays a prompt and advice only for people using incompatible browsers. It appears to be reasonably configurable.
